# Generated by Django 5.2.5 on 2026-03-19 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tecnologia", "Tecnologia"),
                            ("negocios", "Negócios"),
                            ("design", "Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("thumbnail", models.URLField(blank=True, default="")),
                ("video_url", models.URLField(blank=True, default="")),
                ("text_content", models.TextField(blank=True, default="")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermediário", "Intermediário"),
                            ("Avançado", "Avançado"),
                        ],
                        default="Iniciante",
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=20)),
                ("tags", models.TextField(blank=True, default="")),
                ("type", models.CharField(default="text", max_length=20)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
